name: CI

on:
  push:
    branches:
      - development

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login container registry
        run: echo ${{ secrets.REGISTRY_PWORD }} | docker login ${{ secrets.SERVER }} -u ${{ secrets.REGISTRY_UNAME }} --password-stdin

      - name: Pull base image
        run: docker pull ${{ secrets.IMAGE }}

      - name: Run robot tests
        run: |
          echo "${{ secrets.TESTS_ENV_FILE }}" | base64 -d > .env
          cp .env backend/
          cp .env frontend/
          docker compose -f docker-compose-tests.yml up --exit-code-from robo
  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Remove Roboroute
        run: sed -i '/Roboroute\|<*Routes>\|Routes,/d' frontend/src/Components/AuthRoutes.js

      - name: Remove File
        run: rm -rf frontend/src/Components/Roboroute.js
