name: CI

on:
  push:
    branches: 
      - main
jobs:  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          echo "${{ secrets.TESTS_ENV_FILE }}" | base64 -d > .env
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: 'allyourbasearebelongtous'
          
      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts
          
      - name: Sync files with rsync
        run: rsync -avz ./.env ${{ secrets.DEPLOY_SSH_USER }}@${{ secrets.SERVER }}:/home/deploytest/perse/
